name: PacketLogger
author: shoghicp
authors: [PocketMine-MP Team, shoghicp]
api: [3.0.0]
version: 1.2.2
main: shoghicp\PacketLogger\PacketLogger
description: Log network packets as you want
website: https://github.com/BlockNetworks/PluginLogger
